/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, ContractRunner } from "ethers";
import type {
  IGmxIou,
  IGmxIouInterface,
} from "../../../gmx/interfaces/IGmxIou";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGmxIou__factory {
  static readonly abi = _abi;
  static createInterface(): IGmxIouInterface {
    return new Interface(_abi) as IGmxIouInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IGmxIou {
    return new Contract(address, _abi, runner) as unknown as IGmxIou;
  }
}
