/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, ContractRunner } from "ethers";
import type { IGLP, IGLPInterface } from "../../../tokens/interfaces/IGLP";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGLP__factory {
  static readonly abi = _abi;
  static createInterface(): IGLPInterface {
    return new Interface(_abi) as IGLPInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IGLP {
    return new Contract(address, _abi, runner) as unknown as IGLP;
  }
}
